
ERROR (2016-01-31 20:52:01,371): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
10: Error: symbol `begin' is already defined
15: Error: symbol `cleanup' is already defined
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
10: Error: symbol `begin' is already defined
15: Error: symbol `cleanup' is already defined


ERROR (2016-01-31 20:52:01,371): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
10: Error: symbol `begin' is already defined
15: Error: symbol `cleanup' is already defined
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
10: Error: symbol `begin' is already defined
15: Error: symbol `cleanup' is already defined


ERROR (2016-01-31 20:59:03,203): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 20:59:03,203): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 20:59:54,615): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 20:59:54,615): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:01:21,803): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:01:21,803): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:02:48,960): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:02:48,960): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:03:07,819): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:03:07,819): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:03:16,339): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:03:16,339): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:03:34,276): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:03:34,276): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:03:48,546): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:03:48,546): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:04:06,687): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:04:06,687): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:06:18,003): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:06:18,003): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:06:50,792): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:06:50,792): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:07:08,700): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:07:08,700): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:07:22,473): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:07:22,473): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:07:36,417): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:07:36,417): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:07:42,563): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:07:42,563): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:07:49,098): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:07:49,098): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:08:26,888): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:08:26,888): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-01-31 21:10:06,355): Assembler messages:
31: Error: Unrecognized opcode: `mr,r3,r23'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
31: Error: Unrecognized opcode: `mr,r3,r23'


ERROR (2016-01-31 21:10:06,355): Assembler messages:
31: Error: Unrecognized opcode: `mr,r3,r23'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
31: Error: Unrecognized opcode: `mr,r3,r23'


ERROR (2016-01-31 21:12:11,216): Assembler messages:
28: Error: Unrecognized opcode: `mr,r3,r23'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
28: Error: Unrecognized opcode: `mr,r3,r23'


ERROR (2016-01-31 21:12:11,216): Assembler messages:
28: Error: Unrecognized opcode: `mr,r3,r23'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
28: Error: Unrecognized opcode: `mr,r3,r23'


ERROR (2016-02-02 17:57:30,151): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-ufiipa\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-ufiipa\\code.bin'

ERROR (2016-02-02 17:57:30,151): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-ufiipa\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-ufiipa\\code.bin'

ERROR (2016-02-05 15:19:13,878): Assembler messages:
1: Error: Unrecognized opcode: `float'
2: Error: Unrecognized opcode: `return'
2: Error: junk at end of line, first unrecognized character is `/'
3: Error: junk at end of line, first unrecognized character is `}'
5: Error: Unrecognized opcode: `int'
7: Error: Unrecognized opcode: `float*'
8: Error: Unrecognized opcode: `int*'
9: Error: junk at end of line, first unrecognized character is `*'
10: Error: junk at end of line, first unrecognized character is `*'
12: Error: junk at end of line, first unrecognized character is `}'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
1: Error: Unrecognized opcode: `float'
2: Error: Unrecognized opcode: `return'
2: Error: junk at end of line, first unrecognized character is `/'
3: Error: junk at end of line, first unrecognized character is `}'
5: Error: Unrecognized opcode: `int'
7: Error: Unrecognized opcode: `float*'
8: Error: Unrecognized opcode: `int*'
9: Error: junk at end of line, first unrecognized character is `*'
10: Error: junk at end of line, first unrecognized character is `*'
12: Error: junk at end of line, first unrecognized character is `}'


ERROR (2016-02-05 15:19:13,878): Assembler messages:
1: Error: Unrecognized opcode: `float'
2: Error: Unrecognized opcode: `return'
2: Error: junk at end of line, first unrecognized character is `/'
3: Error: junk at end of line, first unrecognized character is `}'
5: Error: Unrecognized opcode: `int'
7: Error: Unrecognized opcode: `float*'
8: Error: Unrecognized opcode: `int*'
9: Error: junk at end of line, first unrecognized character is `*'
10: Error: junk at end of line, first unrecognized character is `*'
12: Error: junk at end of line, first unrecognized character is `}'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
1: Error: Unrecognized opcode: `float'
2: Error: Unrecognized opcode: `return'
2: Error: junk at end of line, first unrecognized character is `/'
3: Error: junk at end of line, first unrecognized character is `}'
5: Error: Unrecognized opcode: `int'
7: Error: Unrecognized opcode: `float*'
8: Error: Unrecognized opcode: `int*'
9: Error: junk at end of line, first unrecognized character is `*'
10: Error: junk at end of line, first unrecognized character is `*'
12: Error: junk at end of line, first unrecognized character is `}'


ERROR (2016-02-05 15:25:30,049): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-02-05 15:25:30,049): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-02-05 16:26:20,421): Assembler messages:
7: Error: Unrecognized opcode: `int'
8: Error: Unrecognized opcode: `void'
9: Error: Unrecognized opcode: `void'
10: Error: Unrecognized opcode: `void'
11: Error: Unrecognized opcode: `void'
12: Error: Unrecognized opcode: `uint32_t'
14: Error: Unrecognized opcode: `void'
37: Error: Unrecognized opcode: `uint32_t*'
38: Error: junk at end of line, first unrecognized character is `*'
39: Error: junk at end of line, first unrecognized character is `}'
41: Error: Unrecognized opcode: `uint32_t'
42: Error: Unrecognized opcode: `return'
43: Error: junk at end of line, first unrecognized character is `}'
63: Error: Unrecognized opcode: `void'
64: Error: Unrecognized opcode: `uint32_t*'
65: Error: Unrecognized opcode: `if'
65: Error: junk at end of line, first unrecognized character is `}'
66: Error: Unrecognized opcode: `else'
66: Error: junk at end of line, first unrecognized character is `}'
67: Error: Unrecognized opcode: `else'
67: Error: junk at end of line, first unrecognized character is `}'
68: Error: Unrecognized opcode: `else'
68: Error: junk at end of line, first unrecognized character is `}'
69: Error: Unrecognized opcode: `else'
69: Error: junk at end of line, first unrecognized character is `}'
70: Error: junk at end of line, first unrecognized character is `}'
72: Error: Unrecognized opcode: `void'
73: Error: Unrecognized opcode: `uint32_t*'
74: Error: junk at end of line, first unrecognized character is `*'
75: Error: junk at end of line, first unrecognized character is `}'
77: Error: junk at end of line, first unrecognized character is `/'
78: Error: Unrecognized opcode: `void'
101: Error: junk at end of line, first unrecognized character is `}'
103: Error: Unrecognized opcode: `void'
104: Error: Unrecognized opcode: `uint32_t*'
105: Error: Unrecognized opcode: `uint32_t*'
106: Error: junk at end of line, first unrecognized character is `*'
107: Error: junk at end of line, first unrecognized character is `*'
108: Error: junk at end of line, first unrecognized character is `}'
110: Error: Unrecognized opcode: `void'
111: Error: Unrecognized opcode: `uint32_t*'
112: Error: Unrecognized opcode: `uint32_t*'
113: Error: junk at end of line, first unrecognized character is `*'
114: Error: junk at end of line, first unrecognized character is `*'
115: Error: junk at end of line, first unrecognized character is `*'
116: Error: junk at end of line, first unrecognized character is `}'
118: Error: Unrecognized opcode: `void'
119: Error: Unrecognized opcode: `if'
119: Error: junk at end of line, first unrecognized character is `}'
120: Error: Unrecognized opcode: `else'
120: Error: junk at end of line, first unrecognized character is `}'
121: Error: Unrecognized opcode: `else'
121: Error: junk at end of line, first unrecognized character is `}'
122: Error: Unrecognized opcode: `else'
122: Error: junk at end of line, first unrecognized character is `}'
123: Error: junk at end of line, first unrecognized character is `}'
151: Error: Unrecognized opcode: `uint32_t'
152: Error: Unrecognized opcode: `if'
153: Error: Unrecognized opcode: `return'
154: Error: junk at end of line, first unrecognized character is `}'
155: Error: Unrecognized opcode: `return'
156: Error: junk at end of line, first unrecognized character is `}'
157: Error: junk at end of line, first unrecognized character is `}'
159: Error: Unrecognized opcode: `int'
160: Error: Unrecognized opcode: `return'
161: Error: junk at end of line, first unrecognized character is `}'
163: Error: junk at end of line, first unrecognized character is `/'
164: Error: Unrecognized opcode: `int'
165: Error: Unrecognized opcode: `uint32_t'
166: Error: Unrecognized opcode: `return'
167: Error: junk at end of line, first unrecognized character is `}'
169: Error: Unrecognized opcode: `int'
170: Error: Unrecognized opcode: `return'
171: Error: junk at end of line, first unrecognized character is `}'
173: Error: Unrecognized opcode: `int'
174: Error: Unrecognized opcode: `return'
175: Error: junk at end of line, first unrecognized character is `}'
177: Error: Unrecognized opcode: `int'
178: Error: Unrecognized opcode: `return'
179: Error: junk at end of line, first unrecognized character is `}'
181: Error: Unrecognized opcode: `int'
182: Error: Unrecognized opcode: `return'
183: Error: junk at end of line, first unrecognized character is `}'
185: Error: Unrecognized opcode: `int'
186: Error: Unrecognized opcode: `return'
186: Error: junk at end of line, first unrecognized character is `/'
187: Error: junk at end of line, first unrecognized character is `}'
189: Error: Unrecognized opcode: `int'
190: Error: Unrecognized opcode: `if'
190: Error: junk at end of line, first unrecognized character is `}'
191: Error: Unrecognized opcode: `else'
191: Error: junk at end of line, first unrecognized character is `}'
192: Error: Unrecognized opcode: `else'
192: Error: junk at end of line, first unrecognized character is `}'
193: Error: Unrecognized opcode: `else'
193: Error: junk at end of line, first unrecognized character is `}'
194: Error: Unrecognized opcode: `else'
194: Error: junk at end of line, first unrecognized character is `}'
195: Error: Unrecognized opcode: `else'
195: Error: junk at end of line, first unrecognized character is `}'
196: Error: Unrecognized opcode: `else'
196: Error: junk at end of line, first unrecognized character is `}'
197: Error: junk at end of line, first unrecognized character is `}'
205: Error: Unrecognized opcode: `void'
206: Error: Unrecognized opcode: `int*'
207: Error: Unrecognized opcode: `int*'
208: Error: Unrecognized opcode: `queue[(*size)++]'
209: Error: Unrecognized opcode: `queue[(*size)++]'
210: Error: junk at end of line, first unrecognized character is `}'
212: Error: Unrecognized opcode: `void'
214: Error: junk at end of line, first unrecognized character is `/'
215: Error: junk at end of line, first unrecognized character is `/'
216: Error: junk at end of line, first unrecognized character is `/'
217: Error: Unrecognized opcode: `void'
218: Error: Unrecognized opcode: `int*'
219: Error: Unrecognized opcode: `int*'
220: Error: Unrecognized opcode: `for'
220: Error: Unrecognized opcode: `i'
220: Error: Unrecognized opcode: `i++)'
221: Error: Unrecognized opcode: `if'
222: Error: junk at end of line, first unrecognized character is `*'
223: Error: Unrecognized opcode: `ai_func_call(queue[i])'
224: Error: junk at end of line, first unrecognized character is `}'
225: Error: junk at end of line, first unrecognized character is `}'
226: Error: junk at end of line, first unrecognized character is `}'
235: Error: Unrecognized opcode: `void'
236: Error: Unrecognized opcode: `uint32_t*'
237: Error: Unrecognized opcode: `int*'
238: Error: Unrecognized opcode: `p_queue[(*p_size)++]'
239: Error: Unrecognized opcode: `p_queue[(*p_size)++]'
240: Error: Unrecognized opcode: `p_queue[(*p_size)++]'
241: Error: junk at end of line, first unrecognized character is `}'
243: Error: Unrecognized opcode: `void'
244: Error: Unrecognized opcode: `int*'
245: Error: Unrecognized opcode: `int'
246: Error: Unrecognized opcode: `if'
247: Error: Unrecognized opcode: `int*'
248: Error: Unrecognized opcode: `uint32_t*'
249: Error: Unrecognized opcode: `while'
250: Error: Unrecognized opcode: `controller_func_call(*(p_queue'
251: Error: junk at end of line, first unrecognized character is `*'
252: Error: Unrecognized opcode: `size--'
253: Error: junk at end of line, first unrecognized character is `}'
254: Error: junk at end of line, first unrecognized character is `}'
255: Error: junk at end of line, first unrecognized character is `}'
270: Error: junk at end of line, first unrecognized character is `/'
271: Error: Unrecognized opcode: `void'
273: Error: Unrecognized opcode: `uint32_t'
275: Error: Unrecognized opcode: `iq_addinput(cur_frame,'
275: Error: junk at end of line, first unrecognized character is `/'
276: Error: Unrecognized opcode: `iq_addinput(cur_frame,'
276: Error: junk at end of line, first unrecognized character is `/'
277: Error: Unrecognized opcode: `iq_addinput(cur_frame'
277: Error: junk at end of line, first unrecognized character is `/'
278: Error: Unrecognized opcode: `iq_addinput(cur_frame'
278: Error: junk at end of line, first unrecognized character is `/'
280: Error: junk at end of line, first unrecognized character is `}'
289: Error: junk at end of line, first unrecognized character is `/'
290: Error: junk at end of line, first unrecognized character is `/'
291: Error: Unrecognized opcode: `void'
292: Error: Unrecognized opcode: `eq_addevent(6,'
293: Error: junk at end of line, first unrecognized character is `}'
295: Error: Unrecognized opcode: `void'
297: Error: Unrecognized opcode: `uint32_t*'
298: Error: Unrecognized opcode: `uint32_t'
299: Error: Unrecognized opcode: `int'
300: Error: Unrecognized opcode: `if'
302: Error: junk at end of line, first unrecognized character is `}'
304: Error: junk at end of line, first unrecognized character is `}'
306: Error: junk at end of line, first unrecognized character is `}'
307: Error: Unrecognized opcode: `move_hittech(dir)'
309: Error: junk at end of line, first unrecognized character is `}'
311: Error: Unrecognized opcode: `void'
312: Error: Unrecognized opcode: `if'
312: Error: junk at end of line, first unrecognized character is `}'
313: Error: Unrecognized opcode: `else'
313: Error: junk at end of line, first unrecognized character is `}'
314: Error: junk at end of line, first unrecognized character is `}'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
7: Error: Unrecognized opcode: `int'
8: Error: Unrecognized opcode: `void'
9: Error: Unrecognized opcode: `void'
10: Error: Unrecognized opcode: `void'
11: Error: Unrecognized opcode: `void'
12: Error: Unrecognized opcode: `uint32_t'
14: Error: Unrecognized opcode: `void'
37: Error: Unrecognized opcode: `uint32_t*'
38: Error: junk at end of line, first unrecognized character is `*'
39: Error: junk at end of line, first unrecognized character is `}'
41: Error: Unrecognized opcode: `uint32_t'
42: Error: Unrecognized opcode: `return'
43: Error: junk at end of line, first unrecognized character is `}'
63: Error: Unrecognized opcode: `void'
64: Error: Unrecognized opcode: `uint32_t*'
65: Error: Unrecognized opcode: `if'
65: Error: junk at end of line, first unrecognized character is `}'
66: Error: Unrecognized opcode: `else'
66: Error: junk at end of line, first unrecognized character is `}'
67: Error: Unrecognized opcode: `else'
67: Error: junk at end of line, first unrecognized character is `}'
68: Error: Unrecognized opcode: `else'
68: Error: junk at end of line, first unrecognized character is `}'
69: Error: Unrecognized opcode: `else'
69: Error: junk at end of line, first unrecognized character is `}'
70: Error: junk at end of line, first unrecognized character is `}'
72: Error: Unrecognized opcode: `void'
73: Error: Unrecognized opcode: `uint32_t*'
74: Error: junk at end of line, first unrecognized character is `*'
75: Error: junk at end of line, first unrecognized character is `}'
77: Error: junk at end of line, first unrecognized character is `/'
78: Error: Unrecognized opcode: `void'
101: Error: junk at end of line, first unrecognized character is `}'
103: Error: Unrecognized opcode: `void'
104: Error: Unrecognized opcode: `uint32_t*'
105: Error: Unrecognized opcode: `uint32_t*'
106: Error: junk at end of line, first unrecognized character is `*'
107: Error: junk at end of line, first unrecognized character is `*'
108: Error: junk at end of line, first unrecognized character is `}'
110: Error: Unrecognized opcode: `void'
111: Error: Unrecognized opcode: `uint32_t*'
112: Error: Unrecognized opcode: `uint32_t*'
113: Error: junk at end of line, first unrecognized character is `*'
114: Error: junk at end of line, first unrecognized character is `*'
115: Error: junk at end of line, first unrecognized character is `*'
116: Error: junk at end of line, first unrecognized character is `}'
118: Error: Unrecognized opcode: `void'
119: Error: Unrecognized opcode: `if'
119: Error: junk at end of line, first unrecognized character is `}'
120: Error: Unrecognized opcode: `else'
120: Error: junk at end of line, first unrecognized character is `}'
121: Error: Unrecognized opcode: `else'
121: Error: junk at end of line, first unrecognized character is `}'
122: Error: Unrecognized opcode: `else'
122: Error: junk at end of line, first unrecognized character is `}'
123: Error: junk at end of line, first unrecognized character is `}'
151: Error: Unrecognized opcode: `uint32_t'
152: Error: Unrecognized opcode: `if'
153: Error: Unrecognized opcode: `return'
154: Error: junk at end of line, first unrecognized character is `}'
155: Error: Unrecognized opcode: `return'
156: Error: junk at end of line, first unrecognized character is `}'
157: Error: junk at end of line, first unrecognized character is `}'
159: Error: Unrecognized opcode: `int'
160: Error: Unrecognized opcode: `return'
161: Error: junk at end of line, first unrecognized character is `}'
163: Error: junk at end of line, first unrecognized character is `/'
164: Error: Unrecognized opcode: `int'
165: Error: Unrecognized opcode: `uint32_t'
166: Error: Unrecognized opcode: `return'
167: Error: junk at end of line, first unrecognized character is `}'
169: Error: Unrecognized opcode: `int'
170: Error: Unrecognized opcode: `return'
171: Error: junk at end of line, first unrecognized character is `}'
173: Error: Unrecognized opcode: `int'
174: Error: Unrecognized opcode: `return'
175: Error: junk at end of line, first unrecognized character is `}'
177: Error: Unrecognized opcode: `int'
178: Error: Unrecognized opcode: `return'
179: Error: junk at end of line, first unrecognized character is `}'
181: Error: Unrecognized opcode: `int'
182: Error: Unrecognized opcode: `return'
183: Error: junk at end of line, first unrecognized character is `}'
185: Error: Unrecognized opcode: `int'
186: Error: Unrecognized opcode: `return'
186: Error: junk at end of line, first unrecognized character is `/'
187: Error: junk at end of line, first unrecognized character is `}'
189: Error: Unrecognized opcode: `int'
190: Error: Unrecognized opcode: `if'
190: Error: junk at end of line, first unrecognized character is `}'
191: Error: Unrecognized opcode: `else'
191: Error: junk at end of line, first unrecognized character is `}'
192: Error: Unrecognized opcode: `else'
192: Error: junk at end of line, first unrecognized character is `}'
193: Error: Unrecognized opcode: `else'
193: Error: junk at end of line, first unrecognized character is `}'
194: Error: Unrecognized opcode: `else'
194: Error: junk at end of line, first unrecognized character is `}'
195: Error: Unrecognized opcode: `else'
195: Error: junk at end of line, first unrecognized character is `}'
196: Error: Unrecognized opcode: `else'
196: Error: junk at end of line, first unrecognized character is `}'
197: Error: junk at end of line, first unrecognized character is `}'
205: Error: Unrecognized opcode: `void'
206: Error: Unrecognized opcode: `int*'
207: Error: Unrecognized opcode: `int*'
208: Error: Unrecognized opcode: `queue[(*size)++]'
209: Error: Unrecognized opcode: `queue[(*size)++]'
210: Error: junk at end of line, first unrecognized character is `}'
212: Error: Unrecognized opcode: `void'
214: Error: junk at end of line, first unrecognized character is `/'
215: Error: junk at end of line, first unrecognized character is `/'
216: Error: junk at end of line, first unrecognized character is `/'
217: Error: Unrecognized opcode: `void'
218: Error: Unrecognized opcode: `int*'
219: Error: Unrecognized opcode: `int*'
220: Error: Unrecognized opcode: `for'
220: Error: Unrecognized opcode: `i'
220: Error: Unrecognized opcode: `i++)'
221: Error: Unrecognized opcode: `if'
222: Error: junk at end of line, first unrecognized character is `*'
223: Error: Unrecognized opcode: `ai_func_call(queue[i])'
224: Error: junk at end of line, first unrecognized character is `}'
225: Error: junk at end of line, first unrecognized character is `}'
226: Error: junk at end of line, first unrecognized character is `}'
235: Error: Unrecognized opcode: `void'
236: Error: Unrecognized opcode: `uint32_t*'
237: Error: Unrecognized opcode: `int*'
238: Error: Unrecognized opcode: `p_queue[(*p_size)++]'
239: Error: Unrecognized opcode: `p_queue[(*p_size)++]'
240: Error: Unrecognized opcode: `p_queue[(*p_size)++]'
241: Error: junk at end of line, first unrecognized character is `}'
243: Error: Unrecognized opcode: `void'
244: Error: Unrecognized opcode: `int*'
245: Error: Unrecognized opcode: `int'
246: Error: Unrecognized opcode: `if'
247: Error: Unrecognized opcode: `int*'
248: Error: Unrecognized opcode: `uint32_t*'
249: Error: Unrecognized opcode: `while'
250: Error: Unrecognized opcode: `controller_func_call(*(p_queue'
251: Error: junk at end of line, first unrecognized character is `*'
252: Error: Unrecognized opcode: `size--'
253: Error: junk at end of line, first unrecognized character is `}'
254: Error: junk at end of line, first unrecognized character is `}'
255: Error: junk at end of line, first unrecognized character is `}'
270: Error: junk at end of line, first unrecognized character is `/'
271: Error: Unrecognized opcode: `void'
273: Error: Unrecognized opcode: `uint32_t'
275: Error: Unrecognized opcode: `iq_addinput(cur_frame,'
275: Error: junk at end of line, first unrecognized character is `/'
276: Error: Unrecognized opcode: `iq_addinput(cur_frame,'
276: Error: junk at end of line, first unrecognized character is `/'
277: Error: Unrecognized opcode: `iq_addinput(cur_frame'
277: Error: junk at end of line, first unrecognized character is `/'
278: Error: Unrecognized opcode: `iq_addinput(cur_frame'
278: Error: junk at end of line, first unrecognized character is `/'
280: Error: junk at end of line, first unrecognized character is `}'
289: Error: junk at end of line, first unrecognized character is `/'
290: Error: junk at end of line, first unrecognized character is `/'
291: Error: Unrecognized opcode: `void'
292: Error: Unrecognized opcode: `eq_addevent(6,'
293: Error: junk at end of line, first unrecognized character is `}'
295: Error: Unrecognized opcode: `void'
297: Error: Unrecognized opcode: `uint32_t*'
298: Error: Unrecognized opcode: `uint32_t'
299: Error: Unrecognized opcode: `int'
300: Error: Unrecognized opcode: `if'
302: Error: junk at end of line, first unrecognized character is `}'
304: Error: junk at end of line, first unrecognized character is `}'
306: Error: junk at end of line, first unrecognized character is `}'
307: Error: Unrecognized opcode: `move_hittech(dir)'
309: Error: junk at end of line, first unrecognized character is `}'
311: Error: Unrecognized opcode: `void'
312: Error: Unrecognized opcode: `if'
312: Error: junk at end of line, first unrecognized character is `}'
313: Error: Unrecognized opcode: `else'
313: Error: junk at end of line, first unrecognized character is `}'
314: Error: junk at end of line, first unrecognized character is `}'


ERROR (2016-02-05 16:26:20,421): Assembler messages:
7: Error: Unrecognized opcode: `int'
8: Error: Unrecognized opcode: `void'
9: Error: Unrecognized opcode: `void'
10: Error: Unrecognized opcode: `void'
11: Error: Unrecognized opcode: `void'
12: Error: Unrecognized opcode: `uint32_t'
14: Error: Unrecognized opcode: `void'
37: Error: Unrecognized opcode: `uint32_t*'
38: Error: junk at end of line, first unrecognized character is `*'
39: Error: junk at end of line, first unrecognized character is `}'
41: Error: Unrecognized opcode: `uint32_t'
42: Error: Unrecognized opcode: `return'
43: Error: junk at end of line, first unrecognized character is `}'
63: Error: Unrecognized opcode: `void'
64: Error: Unrecognized opcode: `uint32_t*'
65: Error: Unrecognized opcode: `if'
65: Error: junk at end of line, first unrecognized character is `}'
66: Error: Unrecognized opcode: `else'
66: Error: junk at end of line, first unrecognized character is `}'
67: Error: Unrecognized opcode: `else'
67: Error: junk at end of line, first unrecognized character is `}'
68: Error: Unrecognized opcode: `else'
68: Error: junk at end of line, first unrecognized character is `}'
69: Error: Unrecognized opcode: `else'
69: Error: junk at end of line, first unrecognized character is `}'
70: Error: junk at end of line, first unrecognized character is `}'
72: Error: Unrecognized opcode: `void'
73: Error: Unrecognized opcode: `uint32_t*'
74: Error: junk at end of line, first unrecognized character is `*'
75: Error: junk at end of line, first unrecognized character is `}'
77: Error: junk at end of line, first unrecognized character is `/'
78: Error: Unrecognized opcode: `void'
101: Error: junk at end of line, first unrecognized character is `}'
103: Error: Unrecognized opcode: `void'
104: Error: Unrecognized opcode: `uint32_t*'
105: Error: Unrecognized opcode: `uint32_t*'
106: Error: junk at end of line, first unrecognized character is `*'
107: Error: junk at end of line, first unrecognized character is `*'
108: Error: junk at end of line, first unrecognized character is `}'
110: Error: Unrecognized opcode: `void'
111: Error: Unrecognized opcode: `uint32_t*'
112: Error: Unrecognized opcode: `uint32_t*'
113: Error: junk at end of line, first unrecognized character is `*'
114: Error: junk at end of line, first unrecognized character is `*'
115: Error: junk at end of line, first unrecognized character is `*'
116: Error: junk at end of line, first unrecognized character is `}'
118: Error: Unrecognized opcode: `void'
119: Error: Unrecognized opcode: `if'
119: Error: junk at end of line, first unrecognized character is `}'
120: Error: Unrecognized opcode: `else'
120: Error: junk at end of line, first unrecognized character is `}'
121: Error: Unrecognized opcode: `else'
121: Error: junk at end of line, first unrecognized character is `}'
122: Error: Unrecognized opcode: `else'
122: Error: junk at end of line, first unrecognized character is `}'
123: Error: junk at end of line, first unrecognized character is `}'
151: Error: Unrecognized opcode: `uint32_t'
152: Error: Unrecognized opcode: `if'
153: Error: Unrecognized opcode: `return'
154: Error: junk at end of line, first unrecognized character is `}'
155: Error: Unrecognized opcode: `return'
156: Error: junk at end of line, first unrecognized character is `}'
157: Error: junk at end of line, first unrecognized character is `}'
159: Error: Unrecognized opcode: `int'
160: Error: Unrecognized opcode: `return'
161: Error: junk at end of line, first unrecognized character is `}'
163: Error: junk at end of line, first unrecognized character is `/'
164: Error: Unrecognized opcode: `int'
165: Error: Unrecognized opcode: `uint32_t'
166: Error: Unrecognized opcode: `return'
167: Error: junk at end of line, first unrecognized character is `}'
169: Error: Unrecognized opcode: `int'
170: Error: Unrecognized opcode: `return'
171: Error: junk at end of line, first unrecognized character is `}'
173: Error: Unrecognized opcode: `int'
174: Error: Unrecognized opcode: `return'
175: Error: junk at end of line, first unrecognized character is `}'
177: Error: Unrecognized opcode: `int'
178: Error: Unrecognized opcode: `return'
179: Error: junk at end of line, first unrecognized character is `}'
181: Error: Unrecognized opcode: `int'
182: Error: Unrecognized opcode: `return'
183: Error: junk at end of line, first unrecognized character is `}'
185: Error: Unrecognized opcode: `int'
186: Error: Unrecognized opcode: `return'
186: Error: junk at end of line, first unrecognized character is `/'
187: Error: junk at end of line, first unrecognized character is `}'
189: Error: Unrecognized opcode: `int'
190: Error: Unrecognized opcode: `if'
190: Error: junk at end of line, first unrecognized character is `}'
191: Error: Unrecognized opcode: `else'
191: Error: junk at end of line, first unrecognized character is `}'
192: Error: Unrecognized opcode: `else'
192: Error: junk at end of line, first unrecognized character is `}'
193: Error: Unrecognized opcode: `else'
193: Error: junk at end of line, first unrecognized character is `}'
194: Error: Unrecognized opcode: `else'
194: Error: junk at end of line, first unrecognized character is `}'
195: Error: Unrecognized opcode: `else'
195: Error: junk at end of line, first unrecognized character is `}'
196: Error: Unrecognized opcode: `else'
196: Error: junk at end of line, first unrecognized character is `}'
197: Error: junk at end of line, first unrecognized character is `}'
205: Error: Unrecognized opcode: `void'
206: Error: Unrecognized opcode: `int*'
207: Error: Unrecognized opcode: `int*'
208: Error: Unrecognized opcode: `queue[(*size)++]'
209: Error: Unrecognized opcode: `queue[(*size)++]'
210: Error: junk at end of line, first unrecognized character is `}'
212: Error: Unrecognized opcode: `void'
214: Error: junk at end of line, first unrecognized character is `/'
215: Error: junk at end of line, first unrecognized character is `/'
216: Error: junk at end of line, first unrecognized character is `/'
217: Error: Unrecognized opcode: `void'
218: Error: Unrecognized opcode: `int*'
219: Error: Unrecognized opcode: `int*'
220: Error: Unrecognized opcode: `for'
220: Error: Unrecognized opcode: `i'
220: Error: Unrecognized opcode: `i++)'
221: Error: Unrecognized opcode: `if'
222: Error: junk at end of line, first unrecognized character is `*'
223: Error: Unrecognized opcode: `ai_func_call(queue[i])'
224: Error: junk at end of line, first unrecognized character is `}'
225: Error: junk at end of line, first unrecognized character is `}'
226: Error: junk at end of line, first unrecognized character is `}'
235: Error: Unrecognized opcode: `void'
236: Error: Unrecognized opcode: `uint32_t*'
237: Error: Unrecognized opcode: `int*'
238: Error: Unrecognized opcode: `p_queue[(*p_size)++]'
239: Error: Unrecognized opcode: `p_queue[(*p_size)++]'
240: Error: Unrecognized opcode: `p_queue[(*p_size)++]'
241: Error: junk at end of line, first unrecognized character is `}'
243: Error: Unrecognized opcode: `void'
244: Error: Unrecognized opcode: `int*'
245: Error: Unrecognized opcode: `int'
246: Error: Unrecognized opcode: `if'
247: Error: Unrecognized opcode: `int*'
248: Error: Unrecognized opcode: `uint32_t*'
249: Error: Unrecognized opcode: `while'
250: Error: Unrecognized opcode: `controller_func_call(*(p_queue'
251: Error: junk at end of line, first unrecognized character is `*'
252: Error: Unrecognized opcode: `size--'
253: Error: junk at end of line, first unrecognized character is `}'
254: Error: junk at end of line, first unrecognized character is `}'
255: Error: junk at end of line, first unrecognized character is `}'
270: Error: junk at end of line, first unrecognized character is `/'
271: Error: Unrecognized opcode: `void'
273: Error: Unrecognized opcode: `uint32_t'
275: Error: Unrecognized opcode: `iq_addinput(cur_frame,'
275: Error: junk at end of line, first unrecognized character is `/'
276: Error: Unrecognized opcode: `iq_addinput(cur_frame,'
276: Error: junk at end of line, first unrecognized character is `/'
277: Error: Unrecognized opcode: `iq_addinput(cur_frame'
277: Error: junk at end of line, first unrecognized character is `/'
278: Error: Unrecognized opcode: `iq_addinput(cur_frame'
278: Error: junk at end of line, first unrecognized character is `/'
280: Error: junk at end of line, first unrecognized character is `}'
289: Error: junk at end of line, first unrecognized character is `/'
290: Error: junk at end of line, first unrecognized character is `/'
291: Error: Unrecognized opcode: `void'
292: Error: Unrecognized opcode: `eq_addevent(6,'
293: Error: junk at end of line, first unrecognized character is `}'
295: Error: Unrecognized opcode: `void'
297: Error: Unrecognized opcode: `uint32_t*'
298: Error: Unrecognized opcode: `uint32_t'
299: Error: Unrecognized opcode: `int'
300: Error: Unrecognized opcode: `if'
302: Error: junk at end of line, first unrecognized character is `}'
304: Error: junk at end of line, first unrecognized character is `}'
306: Error: junk at end of line, first unrecognized character is `}'
307: Error: Unrecognized opcode: `move_hittech(dir)'
309: Error: junk at end of line, first unrecognized character is `}'
311: Error: Unrecognized opcode: `void'
312: Error: Unrecognized opcode: `if'
312: Error: junk at end of line, first unrecognized character is `}'
313: Error: Unrecognized opcode: `else'
313: Error: junk at end of line, first unrecognized character is `}'
314: Error: junk at end of line, first unrecognized character is `}'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
7: Error: Unrecognized opcode: `int'
8: Error: Unrecognized opcode: `void'
9: Error: Unrecognized opcode: `void'
10: Error: Unrecognized opcode: `void'
11: Error: Unrecognized opcode: `void'
12: Error: Unrecognized opcode: `uint32_t'
14: Error: Unrecognized opcode: `void'
37: Error: Unrecognized opcode: `uint32_t*'
38: Error: junk at end of line, first unrecognized character is `*'
39: Error: junk at end of line, first unrecognized character is `}'
41: Error: Unrecognized opcode: `uint32_t'
42: Error: Unrecognized opcode: `return'
43: Error: junk at end of line, first unrecognized character is `}'
63: Error: Unrecognized opcode: `void'
64: Error: Unrecognized opcode: `uint32_t*'
65: Error: Unrecognized opcode: `if'
65: Error: junk at end of line, first unrecognized character is `}'
66: Error: Unrecognized opcode: `else'
66: Error: junk at end of line, first unrecognized character is `}'
67: Error: Unrecognized opcode: `else'
67: Error: junk at end of line, first unrecognized character is `}'
68: Error: Unrecognized opcode: `else'
68: Error: junk at end of line, first unrecognized character is `}'
69: Error: Unrecognized opcode: `else'
69: Error: junk at end of line, first unrecognized character is `}'
70: Error: junk at end of line, first unrecognized character is `}'
72: Error: Unrecognized opcode: `void'
73: Error: Unrecognized opcode: `uint32_t*'
74: Error: junk at end of line, first unrecognized character is `*'
75: Error: junk at end of line, first unrecognized character is `}'
77: Error: junk at end of line, first unrecognized character is `/'
78: Error: Unrecognized opcode: `void'
101: Error: junk at end of line, first unrecognized character is `}'
103: Error: Unrecognized opcode: `void'
104: Error: Unrecognized opcode: `uint32_t*'
105: Error: Unrecognized opcode: `uint32_t*'
106: Error: junk at end of line, first unrecognized character is `*'
107: Error: junk at end of line, first unrecognized character is `*'
108: Error: junk at end of line, first unrecognized character is `}'
110: Error: Unrecognized opcode: `void'
111: Error: Unrecognized opcode: `uint32_t*'
112: Error: Unrecognized opcode: `uint32_t*'
113: Error: junk at end of line, first unrecognized character is `*'
114: Error: junk at end of line, first unrecognized character is `*'
115: Error: junk at end of line, first unrecognized character is `*'
116: Error: junk at end of line, first unrecognized character is `}'
118: Error: Unrecognized opcode: `void'
119: Error: Unrecognized opcode: `if'
119: Error: junk at end of line, first unrecognized character is `}'
120: Error: Unrecognized opcode: `else'
120: Error: junk at end of line, first unrecognized character is `}'
121: Error: Unrecognized opcode: `else'
121: Error: junk at end of line, first unrecognized character is `}'
122: Error: Unrecognized opcode: `else'
122: Error: junk at end of line, first unrecognized character is `}'
123: Error: junk at end of line, first unrecognized character is `}'
151: Error: Unrecognized opcode: `uint32_t'
152: Error: Unrecognized opcode: `if'
153: Error: Unrecognized opcode: `return'
154: Error: junk at end of line, first unrecognized character is `}'
155: Error: Unrecognized opcode: `return'
156: Error: junk at end of line, first unrecognized character is `}'
157: Error: junk at end of line, first unrecognized character is `}'
159: Error: Unrecognized opcode: `int'
160: Error: Unrecognized opcode: `return'
161: Error: junk at end of line, first unrecognized character is `}'
163: Error: junk at end of line, first unrecognized character is `/'
164: Error: Unrecognized opcode: `int'
165: Error: Unrecognized opcode: `uint32_t'
166: Error: Unrecognized opcode: `return'
167: Error: junk at end of line, first unrecognized character is `}'
169: Error: Unrecognized opcode: `int'
170: Error: Unrecognized opcode: `return'
171: Error: junk at end of line, first unrecognized character is `}'
173: Error: Unrecognized opcode: `int'
174: Error: Unrecognized opcode: `return'
175: Error: junk at end of line, first unrecognized character is `}'
177: Error: Unrecognized opcode: `int'
178: Error: Unrecognized opcode: `return'
179: Error: junk at end of line, first unrecognized character is `}'
181: Error: Unrecognized opcode: `int'
182: Error: Unrecognized opcode: `return'
183: Error: junk at end of line, first unrecognized character is `}'
185: Error: Unrecognized opcode: `int'
186: Error: Unrecognized opcode: `return'
186: Error: junk at end of line, first unrecognized character is `/'
187: Error: junk at end of line, first unrecognized character is `}'
189: Error: Unrecognized opcode: `int'
190: Error: Unrecognized opcode: `if'
190: Error: junk at end of line, first unrecognized character is `}'
191: Error: Unrecognized opcode: `else'
191: Error: junk at end of line, first unrecognized character is `}'
192: Error: Unrecognized opcode: `else'
192: Error: junk at end of line, first unrecognized character is `}'
193: Error: Unrecognized opcode: `else'
193: Error: junk at end of line, first unrecognized character is `}'
194: Error: Unrecognized opcode: `else'
194: Error: junk at end of line, first unrecognized character is `}'
195: Error: Unrecognized opcode: `else'
195: Error: junk at end of line, first unrecognized character is `}'
196: Error: Unrecognized opcode: `else'
196: Error: junk at end of line, first unrecognized character is `}'
197: Error: junk at end of line, first unrecognized character is `}'
205: Error: Unrecognized opcode: `void'
206: Error: Unrecognized opcode: `int*'
207: Error: Unrecognized opcode: `int*'
208: Error: Unrecognized opcode: `queue[(*size)++]'
209: Error: Unrecognized opcode: `queue[(*size)++]'
210: Error: junk at end of line, first unrecognized character is `}'
212: Error: Unrecognized opcode: `void'
214: Error: junk at end of line, first unrecognized character is `/'
215: Error: junk at end of line, first unrecognized character is `/'
216: Error: junk at end of line, first unrecognized character is `/'
217: Error: Unrecognized opcode: `void'
218: Error: Unrecognized opcode: `int*'
219: Error: Unrecognized opcode: `int*'
220: Error: Unrecognized opcode: `for'
220: Error: Unrecognized opcode: `i'
220: Error: Unrecognized opcode: `i++)'
221: Error: Unrecognized opcode: `if'
222: Error: junk at end of line, first unrecognized character is `*'
223: Error: Unrecognized opcode: `ai_func_call(queue[i])'
224: Error: junk at end of line, first unrecognized character is `}'
225: Error: junk at end of line, first unrecognized character is `}'
226: Error: junk at end of line, first unrecognized character is `}'
235: Error: Unrecognized opcode: `void'
236: Error: Unrecognized opcode: `uint32_t*'
237: Error: Unrecognized opcode: `int*'
238: Error: Unrecognized opcode: `p_queue[(*p_size)++]'
239: Error: Unrecognized opcode: `p_queue[(*p_size)++]'
240: Error: Unrecognized opcode: `p_queue[(*p_size)++]'
241: Error: junk at end of line, first unrecognized character is `}'
243: Error: Unrecognized opcode: `void'
244: Error: Unrecognized opcode: `int*'
245: Error: Unrecognized opcode: `int'
246: Error: Unrecognized opcode: `if'
247: Error: Unrecognized opcode: `int*'
248: Error: Unrecognized opcode: `uint32_t*'
249: Error: Unrecognized opcode: `while'
250: Error: Unrecognized opcode: `controller_func_call(*(p_queue'
251: Error: junk at end of line, first unrecognized character is `*'
252: Error: Unrecognized opcode: `size--'
253: Error: junk at end of line, first unrecognized character is `}'
254: Error: junk at end of line, first unrecognized character is `}'
255: Error: junk at end of line, first unrecognized character is `}'
270: Error: junk at end of line, first unrecognized character is `/'
271: Error: Unrecognized opcode: `void'
273: Error: Unrecognized opcode: `uint32_t'
275: Error: Unrecognized opcode: `iq_addinput(cur_frame,'
275: Error: junk at end of line, first unrecognized character is `/'
276: Error: Unrecognized opcode: `iq_addinput(cur_frame,'
276: Error: junk at end of line, first unrecognized character is `/'
277: Error: Unrecognized opcode: `iq_addinput(cur_frame'
277: Error: junk at end of line, first unrecognized character is `/'
278: Error: Unrecognized opcode: `iq_addinput(cur_frame'
278: Error: junk at end of line, first unrecognized character is `/'
280: Error: junk at end of line, first unrecognized character is `}'
289: Error: junk at end of line, first unrecognized character is `/'
290: Error: junk at end of line, first unrecognized character is `/'
291: Error: Unrecognized opcode: `void'
292: Error: Unrecognized opcode: `eq_addevent(6,'
293: Error: junk at end of line, first unrecognized character is `}'
295: Error: Unrecognized opcode: `void'
297: Error: Unrecognized opcode: `uint32_t*'
298: Error: Unrecognized opcode: `uint32_t'
299: Error: Unrecognized opcode: `int'
300: Error: Unrecognized opcode: `if'
302: Error: junk at end of line, first unrecognized character is `}'
304: Error: junk at end of line, first unrecognized character is `}'
306: Error: junk at end of line, first unrecognized character is `}'
307: Error: Unrecognized opcode: `move_hittech(dir)'
309: Error: junk at end of line, first unrecognized character is `}'
311: Error: Unrecognized opcode: `void'
312: Error: Unrecognized opcode: `if'
312: Error: junk at end of line, first unrecognized character is `}'
313: Error: Unrecognized opcode: `else'
313: Error: junk at end of line, first unrecognized character is `}'
314: Error: junk at end of line, first unrecognized character is `}'


ERROR (2016-02-06 14:54:20,980): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-02-06 14:54:20,980): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-02-06 14:54:51,736): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-02-06 14:54:51,736): Assembler messages:
0: Warning: end of file not at end of a line; newline inserted
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\pyiiasmh_cli.py", line 73, in assemble
    geckocodes = ppctools.asm_opcodes(tmpdir, inputfile, outputfile)
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 103, in asm_opcodes
    raise RuntimeError(errormsg)
RuntimeError: Assembler messages:
0: Warning: end of file not at end of a line; newline inserted


ERROR (2016-02-06 14:55:07,371): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-eavyfa\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-eavyfa\\code.bin'

ERROR (2016-02-06 14:55:07,371): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-eavyfa\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-eavyfa\\code.bin'

ERROR (2016-02-06 14:55:12,045): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-pndxyv\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-pndxyv\\code.bin'

ERROR (2016-02-06 14:55:12,045): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-pndxyv\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-pndxyv\\code.bin'

ERROR (2016-02-06 14:55:45,780): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-r1_1qp\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-r1_1qp\\code.bin'

ERROR (2016-02-06 14:55:45,780): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-r1_1qp\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-r1_1qp\\code.bin'

ERROR (2016-02-06 14:55:58,084): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-vi3gfu\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-vi3gfu\\code.bin'

ERROR (2016-02-06 14:55:58,084): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-vi3gfu\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-vi3gfu\\code.bin'

ERROR (2016-02-13 19:41:35,378): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-rteof9\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-rteof9\\code.bin'

ERROR (2016-02-13 19:41:35,378): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-rteof9\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-rteof9\\code.bin'

ERROR (2016-02-13 22:09:55,868): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-l1eibk\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-l1eibk\\code.bin'

ERROR (2016-02-13 22:09:55,868): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-l1eibk\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-l1eibk\\code.bin'

ERROR (2016-02-13 23:42:46,701): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-0dapx8\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-0dapx8\\code.bin'

ERROR (2016-02-13 23:42:46,701): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-0dapx8\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-0dapx8\\code.bin'

ERROR (2016-02-13 23:43:07,576): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-bepbuk\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-bepbuk\\code.bin'

ERROR (2016-02-13 23:43:07,576): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-bepbuk\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-bepbuk\\code.bin'

ERROR (2016-02-15 03:40:02,151): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-ym1olr\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-ym1olr\\code.bin'

ERROR (2016-02-15 03:40:02,151): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-ym1olr\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-ym1olr\\code.bin'

ERROR (2016-02-16 00:49:24,894): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-hwxgip\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-hwxgip\\code.bin'

ERROR (2016-02-16 00:49:24,894): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-hwxgip\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-hwxgip\\code.bin'

ERROR (2016-02-16 00:49:57,246): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-uewlqz\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-uewlqz\\code.bin'

ERROR (2016-02-16 00:49:57,246): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-uewlqz\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-uewlqz\\code.bin'

ERROR (2016-02-16 00:50:36,493): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-zbcflz\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-zbcflz\\code.bin'

ERROR (2016-02-16 00:50:36,493): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-zbcflz\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-zbcflz\\code.bin'

ERROR (2016-02-16 00:50:50,049): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-gl89bm\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-gl89bm\\code.bin'

ERROR (2016-02-16 00:50:50,049): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-gl89bm\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-gl89bm\\code.bin'

ERROR (2016-02-16 00:51:10,210): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-kp4fyf\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-kp4fyf\\code.bin'

ERROR (2016-02-16 00:51:10,210): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-kp4fyf\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-kp4fyf\\code.bin'

ERROR (2016-02-16 00:52:20,529): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-ggaohu\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-ggaohu\\code.bin'

ERROR (2016-02-16 00:52:20,529): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-ggaohu\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-ggaohu\\code.bin'

ERROR (2016-02-16 00:53:16,913): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-oognhx\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-oognhx\\code.bin'

ERROR (2016-02-16 00:53:16,913): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-oognhx\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-oognhx\\code.bin'

ERROR (2016-02-16 00:56:50,109): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-5zorg4\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-5zorg4\\code.bin'

ERROR (2016-02-16 00:56:50,109): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-5zorg4\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-5zorg4\\code.bin'

ERROR (2016-02-16 00:58:03,602): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-h5nbmy\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-h5nbmy\\code.bin'

ERROR (2016-02-16 00:58:03,602): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-h5nbmy\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-h5nbmy\\code.bin'

ERROR (2016-02-16 19:46:08,641): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-iwq3gu\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-iwq3gu\\code.bin'

ERROR (2016-02-16 19:46:08,641): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-iwq3gu\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-iwq3gu\\code.bin'

ERROR (2016-02-16 19:46:53,025): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-oxdgzi\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-oxdgzi\\code.bin'

ERROR (2016-02-16 19:46:53,025): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-oxdgzi\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-oxdgzi\\code.bin'

ERROR (2016-02-16 19:50:12,311): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-u7zimx\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-u7zimx\\code.bin'

ERROR (2016-02-16 19:50:12,311): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-u7zimx\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-u7zimx\\code.bin'

ERROR (2016-02-21 02:59:15,842): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-j1b45b\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-j1b45b\\code.bin'

ERROR (2016-02-21 02:59:15,842): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-j1b45b\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-j1b45b\\code.bin'

ERROR (2016-02-27 23:09:23,503): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-uf7tns\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-uf7tns\\code.bin'

ERROR (2016-02-27 23:09:23,503): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-uf7tns\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-uf7tns\\code.bin'

ERROR (2016-02-27 23:45:46,328): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-7tmjxb\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-7tmjxb\\code.bin'

ERROR (2016-02-27 23:45:46,328): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-7tmjxb\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-7tmjxb\\code.bin'

ERROR (2016-02-27 23:46:42,144): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-336itv\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-336itv\\code.bin'

ERROR (2016-02-27 23:46:42,144): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-336itv\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-336itv\\code.bin'

ERROR (2016-02-28 04:02:04,438): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-9ksj7i\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-9ksj7i\\code.bin'

ERROR (2016-02-28 04:02:04,438): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-9ksj7i\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-9ksj7i\\code.bin'

ERROR (2016-03-01 01:33:03,119): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-2eo1_v\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-2eo1_v\\code.bin'

ERROR (2016-03-01 01:33:03,119): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-2eo1_v\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-2eo1_v\\code.bin'

ERROR (2016-03-01 01:35:49,012): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-p14tzu\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-p14tzu\\code.bin'

ERROR (2016-03-01 01:35:49,012): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-p14tzu\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-p14tzu\\code.bin'

ERROR (2016-03-01 06:09:10,414): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-wcefhi\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-wcefhi\\code.bin'

ERROR (2016-03-01 06:09:10,414): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-wcefhi\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-wcefhi\\code.bin'

ERROR (2016-03-02 07:11:16,417): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-2lb1ud\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-2lb1ud\\code.bin'

ERROR (2016-03-02 07:11:16,417): Failed to open 'c:\users\tom\appdata\local\temp\pyiiasmh-2lb1ud\code.bin'
Traceback (most recent call last):
  File "D:\MeleeAI\AI\pyiiasmh\ppctools.py", line 114, in asm_opcodes
    f = open(binfile, "rb")
IOError: [Errno 2] No such file or directory: 'c:\\users\\tom\\appdata\\local\\temp\\pyiiasmh-2lb1ud\\code.bin'
